#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : indi
Version  : 2.0.8
Release  : 9
URL      : https://github.com/indilib/indi/archive/v2.0.8/indi-2.0.8.tar.gz
Source0  : https://github.com/indilib/indi/archive/v2.0.8/indi-2.0.8.tar.gz
Summary  : Instrument Neutral Distributed Interface
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1 MIT
Requires: indi-bin = %{version}-%{release}
Requires: indi-config = %{version}-%{release}
Requires: indi-data = %{version}-%{release}
Requires: indi-lib = %{version}-%{release}
Requires: indi-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : cfitsio-dev
BuildRequires : curl-dev
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : gsl-dev
BuildRequires : libev-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libnova-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(fftw3)
BuildRequires : pkgconfig(gsl)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : qtbase-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
INDI is a distributed control protocol designed to operate
astronomical instrumentation. INDI is small, flexible, easy to parse,
and scalable. It supports common DCS functions such as remote control,
data acquisition, monitoring, and a lot more.

%package bin
Summary: bin components for the indi package.
Group: Binaries
Requires: indi-data = %{version}-%{release}
Requires: indi-config = %{version}-%{release}
Requires: indi-license = %{version}-%{release}

%description bin
bin components for the indi package.


%package config
Summary: config components for the indi package.
Group: Default

%description config
config components for the indi package.


%package data
Summary: data components for the indi package.
Group: Data

%description data
data components for the indi package.


%package dev
Summary: dev components for the indi package.
Group: Development
Requires: indi-lib = %{version}-%{release}
Requires: indi-bin = %{version}-%{release}
Requires: indi-data = %{version}-%{release}
Provides: indi-devel = %{version}-%{release}
Requires: indi = %{version}-%{release}

%description dev
dev components for the indi package.


%package lib
Summary: lib components for the indi package.
Group: Libraries
Requires: indi-data = %{version}-%{release}
Requires: indi-license = %{version}-%{release}

%description lib
lib components for the indi package.


%package license
Summary: license components for the indi package.
Group: Default

%description license
license components for the indi package.


%prep
%setup -q -n indi-2.0.8
cd %{_builddir}/indi-2.0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1717437473
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DLIBEV_INCLUDE_DIR=/usr/include/libev  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DLIBEV_INCLUDE_DIR=/usr/include/libev  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1717437473
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/indi
cp %{_builddir}/indi-%{version}/COPYING.BSD %{buildroot}/usr/share/package-licenses/indi/c237597680be0db41fc5ca7249bc540b8825371e || :
cp %{_builddir}/indi-%{version}/COPYING.GPL %{buildroot}/usr/share/package-licenses/indi/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/indi-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/indi/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/indi-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/indi/85c02e0cb8c0aaac8a3f3eed04bc1a097e145883 || :
cp %{_builddir}/indi-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/indi/b386b371ce94933e63ced1052aa72a60da5485ff || :
cp %{_builddir}/indi-%{version}/libs/httplib/httplib-LICENSE %{buildroot}/usr/share/package-licenses/indi/321af0a4f65053aa5df091a79465916cfb42cea3 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/lib/udev/rules.d/

mv %{buildroot}/lib/udev/rules.d/* %{buildroot}/usr/lib/udev/rules.d/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/usr/lib64/indi/MathPlugins/libindi_Nearest_MathPlugin.so
/V3/usr/usr/lib64/indi/MathPlugins/libindi_SVD_MathPlugin.so
/usr/usr/lib64/indi/MathPlugins/libindi_Nearest_MathPlugin.so
/usr/usr/lib64/indi/MathPlugins/libindi_SVD_MathPlugin.so

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/indi_Excalibur
/V3/usr/bin/indi_aaf2_focus
/V3/usr/bin/indi_activefocuser_focus
/V3/usr/bin/indi_alluna_tcs2
/V3/usr/bin/indi_alto
/V3/usr/bin/indi_arduinost4
/V3/usr/bin/indi_astrolink4mini2
/V3/usr/bin/indi_astromech_lpm
/V3/usr/bin/indi_astrometry
/V3/usr/bin/indi_astrotrac_telescope
/V3/usr/bin/indi_baader_dome
/V3/usr/bin/indi_celestron_gps
/V3/usr/bin/indi_celestron_sct_focus
/V3/usr/bin/indi_cheapodc
/V3/usr/bin/indi_crux_mount
/V3/usr/bin/indi_ddw_dome
/V3/usr/bin/indi_deepskydad_af1_focus
/V3/usr/bin/indi_deepskydad_af2_focus
/V3/usr/bin/indi_deepskydad_af3_focus
/V3/usr/bin/indi_deepskydad_fp1
/V3/usr/bin/indi_deepskydad_fr1
/V3/usr/bin/indi_dmfc_focus
/V3/usr/bin/indi_domepro2_dome
/V3/usr/bin/indi_dragon_light
/V3/usr/bin/indi_dragonlair_dome
/V3/usr/bin/indi_dsc_telescope
/V3/usr/bin/indi_efa_focus
/V3/usr/bin/indi_esatto_focus
/V3/usr/bin/indi_esattoarco_focus
/V3/usr/bin/indi_eval
/V3/usr/bin/indi_falcon_rotator
/V3/usr/bin/indi_fcusb_focus
/V3/usr/bin/indi_flipflat
/V3/usr/bin/indi_gemini_focus
/V3/usr/bin/indi_getprop
/V3/usr/bin/indi_giotto
/V3/usr/bin/indi_gpusb
/V3/usr/bin/indi_hid_test
/V3/usr/bin/indi_hitecastrodc_focus
/V3/usr/bin/indi_ieaf_focus
/V3/usr/bin/indi_ieq_telescope
/V3/usr/bin/indi_ieqlegacy_telescope
/V3/usr/bin/indi_imager_agent
/V3/usr/bin/indi_integra_focus
/V3/usr/bin/indi_ioptronv3_telescope
/V3/usr/bin/indi_joystick
/V3/usr/bin/indi_lacerta_mfoc_fmc_focus
/V3/usr/bin/indi_lacerta_mfoc_focus
/V3/usr/bin/indi_lakeside_focus
/V3/usr/bin/indi_lx200_TeenAstro
/V3/usr/bin/indi_lx200basic
/V3/usr/bin/indi_lx200generic
/V3/usr/bin/indi_lynx_focus
/V3/usr/bin/indi_manual_wheel
/V3/usr/bin/indi_mbox_weather
/V3/usr/bin/indi_meta_weather
/V3/usr/bin/indi_microtouch_focus
/V3/usr/bin/indi_moonlite_focus
/V3/usr/bin/indi_moonlitedro_focus
/V3/usr/bin/indi_myDewControllerPro
/V3/usr/bin/indi_mydcp4esp32
/V3/usr/bin/indi_myfocuserpro2_focus
/V3/usr/bin/indi_nexdome_beaver
/V3/usr/bin/indi_nfocus
/V3/usr/bin/indi_nframe_rotator
/V3/usr/bin/indi_nightcrawler_focus
/V3/usr/bin/indi_nstep_focus
/V3/usr/bin/indi_onfocus_focus
/V3/usr/bin/indi_openweathermap_weather
/V3/usr/bin/indi_optec_wheel
/V3/usr/bin/indi_paramount_telescope
/V3/usr/bin/indi_pegasus_flatmaster
/V3/usr/bin/indi_pegasus_focuscube
/V3/usr/bin/indi_pegasus_focuscube3
/V3/usr/bin/indi_pegasus_ppb
/V3/usr/bin/indi_pegasus_ppba
/V3/usr/bin/indi_pegasus_prodigyMF
/V3/usr/bin/indi_pegasus_scopsoag
/V3/usr/bin/indi_pegasus_spb
/V3/usr/bin/indi_pegasus_uch
/V3/usr/bin/indi_pegasus_upb
/V3/usr/bin/indi_pegasusindigo_wheel
/V3/usr/bin/indi_perfectstar_focus
/V3/usr/bin/indi_planewave_deltat
/V3/usr/bin/indi_planewave_telescope
/V3/usr/bin/indi_pmc8_telescope
/V3/usr/bin/indi_pyxis_rotator
/V3/usr/bin/indi_qhycfw1_wheel
/V3/usr/bin/indi_qhycfw2_wheel
/V3/usr/bin/indi_qhycfw3_wheel
/V3/usr/bin/indi_quantum_wheel
/V3/usr/bin/indi_rainbow_telescope
/V3/usr/bin/indi_rainbowrsf_focus
/V3/usr/bin/indi_rbfocus_focus
/V3/usr/bin/indi_rigel_dome
/V3/usr/bin/indi_robo_focus
/V3/usr/bin/indi_rolloff_dome
/V3/usr/bin/indi_scopedome_dome
/V3/usr/bin/indi_script_dome
/V3/usr/bin/indi_script_telescope
/V3/usr/bin/indi_sestosenso2_focus
/V3/usr/bin/indi_sestosenso_focus
/V3/usr/bin/indi_setprop
/V3/usr/bin/indi_siefs_focus
/V3/usr/bin/indi_simulator_ccd
/V3/usr/bin/indi_simulator_dome
/V3/usr/bin/indi_simulator_focus
/V3/usr/bin/indi_simulator_gps
/V3/usr/bin/indi_simulator_guide
/V3/usr/bin/indi_simulator_lightpanel
/V3/usr/bin/indi_simulator_receiver
/V3/usr/bin/indi_simulator_rotator
/V3/usr/bin/indi_simulator_sqm
/V3/usr/bin/indi_simulator_telescope
/V3/usr/bin/indi_simulator_weather
/V3/usr/bin/indi_simulator_wheel
/V3/usr/bin/indi_skycommander_telescope
/V3/usr/bin/indi_skysafari
/V3/usr/bin/indi_skywatcherAltAzMount
/V3/usr/bin/indi_smartfocus_focus
/V3/usr/bin/indi_snapcap
/V3/usr/bin/indi_sqm_weather
/V3/usr/bin/indi_star2000
/V3/usr/bin/indi_steeldrive2_focus
/V3/usr/bin/indi_steeldrive_focus
/V3/usr/bin/indi_synscan_telescope
/V3/usr/bin/indi_synscanlegacy_telescope
/V3/usr/bin/indi_tcfs_focus
/V3/usr/bin/indi_teenastro_focus
/V3/usr/bin/indi_temma_telescope
/V3/usr/bin/indi_trutech_wheel
/V3/usr/bin/indi_uranus_weather
/V3/usr/bin/indi_usbdewpoint
/V3/usr/bin/indi_usbfocusv3_focus
/V3/usr/bin/indi_v4l2_ccd
/V3/usr/bin/indi_vantage_weather
/V3/usr/bin/indi_wanderer_cover
/V3/usr/bin/indi_wanderer_lite_rotator
/V3/usr/bin/indi_wanderer_rotator_lite_v2
/V3/usr/bin/indi_wanderer_rotator_mini
/V3/usr/bin/indi_wandererbox_plus_v3
/V3/usr/bin/indi_wandererbox_pro_v3
/V3/usr/bin/indi_wanderercover_v4_ec
/V3/usr/bin/indi_watchdog
/V3/usr/bin/indi_watcher_weather
/V3/usr/bin/indi_weather_safety_proxy
/V3/usr/bin/indi_xagyl_wheel
/V3/usr/bin/indiserver
/V3/usr/bin/shelyak_usis
/usr/bin/indi_Excalibur
/usr/bin/indi_aaf2_focus
/usr/bin/indi_activefocuser_focus
/usr/bin/indi_alluna_tcs2
/usr/bin/indi_alto
/usr/bin/indi_arduinost4
/usr/bin/indi_astrolink4mini2
/usr/bin/indi_astromech_lpm
/usr/bin/indi_astrometry
/usr/bin/indi_astrotrac_telescope
/usr/bin/indi_baader_dome
/usr/bin/indi_celestron_gps
/usr/bin/indi_celestron_sct_focus
/usr/bin/indi_cheapodc
/usr/bin/indi_crux_mount
/usr/bin/indi_ddw_dome
/usr/bin/indi_deepskydad_af1_focus
/usr/bin/indi_deepskydad_af2_focus
/usr/bin/indi_deepskydad_af3_focus
/usr/bin/indi_deepskydad_fp1
/usr/bin/indi_deepskydad_fr1
/usr/bin/indi_dmfc_focus
/usr/bin/indi_domepro2_dome
/usr/bin/indi_dragon_light
/usr/bin/indi_dragonlair_dome
/usr/bin/indi_dsc_telescope
/usr/bin/indi_efa_focus
/usr/bin/indi_eq500x_telescope
/usr/bin/indi_esatto_focus
/usr/bin/indi_esattoarco_focus
/usr/bin/indi_eval
/usr/bin/indi_falcon_rotator
/usr/bin/indi_fcusb_focus
/usr/bin/indi_flipflat
/usr/bin/indi_gemini_focus
/usr/bin/indi_getprop
/usr/bin/indi_giotto
/usr/bin/indi_gpusb
/usr/bin/indi_hid_test
/usr/bin/indi_hitecastrodc_focus
/usr/bin/indi_ieaf_focus
/usr/bin/indi_ieq_telescope
/usr/bin/indi_ieqlegacy_telescope
/usr/bin/indi_imager_agent
/usr/bin/indi_integra_focus
/usr/bin/indi_ioptronHC8406
/usr/bin/indi_ioptronv3_telescope
/usr/bin/indi_joystick
/usr/bin/indi_lacerta_mfoc_fmc_focus
/usr/bin/indi_lacerta_mfoc_focus
/usr/bin/indi_lakeside_focus
/usr/bin/indi_lx200_10micron
/usr/bin/indi_lx200_16
/usr/bin/indi_lx200_OnStep
/usr/bin/indi_lx200_OpenAstroTech
/usr/bin/indi_lx200_TeenAstro
/usr/bin/indi_lx200_pegasus_nyx101
/usr/bin/indi_lx200am5
/usr/bin/indi_lx200ap_v2
/usr/bin/indi_lx200autostar
/usr/bin/indi_lx200basic
/usr/bin/indi_lx200classic
/usr/bin/indi_lx200fs2
/usr/bin/indi_lx200gemini
/usr/bin/indi_lx200generic
/usr/bin/indi_lx200gotonova
/usr/bin/indi_lx200gps
/usr/bin/indi_lx200pulsar2
/usr/bin/indi_lx200ss2000pc
/usr/bin/indi_lx200zeq25
/usr/bin/indi_lynx_focus
/usr/bin/indi_manual_wheel
/usr/bin/indi_mbox_weather
/usr/bin/indi_meta_weather
/usr/bin/indi_microtouch_focus
/usr/bin/indi_moonlite_focus
/usr/bin/indi_moonlitedro_focus
/usr/bin/indi_myDewControllerPro
/usr/bin/indi_mydcp4esp32
/usr/bin/indi_myfocuserpro2_focus
/usr/bin/indi_nexdome_beaver
/usr/bin/indi_nfocus
/usr/bin/indi_nframe_rotator
/usr/bin/indi_nightcrawler_focus
/usr/bin/indi_nstep_focus
/usr/bin/indi_onfocus_focus
/usr/bin/indi_openweathermap_weather
/usr/bin/indi_optec_wheel
/usr/bin/indi_paramount_telescope
/usr/bin/indi_pegasus_flatmaster
/usr/bin/indi_pegasus_focuscube
/usr/bin/indi_pegasus_focuscube3
/usr/bin/indi_pegasus_ppb
/usr/bin/indi_pegasus_ppba
/usr/bin/indi_pegasus_prodigyMF
/usr/bin/indi_pegasus_scopsoag
/usr/bin/indi_pegasus_spb
/usr/bin/indi_pegasus_uch
/usr/bin/indi_pegasus_upb
/usr/bin/indi_pegasusindigo_wheel
/usr/bin/indi_perfectstar_focus
/usr/bin/indi_planewave_deltat
/usr/bin/indi_planewave_telescope
/usr/bin/indi_pmc8_telescope
/usr/bin/indi_pyxis_rotator
/usr/bin/indi_qhycfw1_wheel
/usr/bin/indi_qhycfw2_wheel
/usr/bin/indi_qhycfw3_wheel
/usr/bin/indi_quantum_wheel
/usr/bin/indi_rainbow_telescope
/usr/bin/indi_rainbowrsf_focus
/usr/bin/indi_rbfocus_focus
/usr/bin/indi_rigel_dome
/usr/bin/indi_robo_focus
/usr/bin/indi_rolloff_dome
/usr/bin/indi_scopedome_dome
/usr/bin/indi_script_dome
/usr/bin/indi_script_telescope
/usr/bin/indi_sestosenso2_focus
/usr/bin/indi_sestosenso_focus
/usr/bin/indi_setprop
/usr/bin/indi_siefs_focus
/usr/bin/indi_simulator_ccd
/usr/bin/indi_simulator_dome
/usr/bin/indi_simulator_focus
/usr/bin/indi_simulator_gps
/usr/bin/indi_simulator_guide
/usr/bin/indi_simulator_lightpanel
/usr/bin/indi_simulator_receiver
/usr/bin/indi_simulator_rotator
/usr/bin/indi_simulator_sqm
/usr/bin/indi_simulator_telescope
/usr/bin/indi_simulator_weather
/usr/bin/indi_simulator_wheel
/usr/bin/indi_skycommander_telescope
/usr/bin/indi_skysafari
/usr/bin/indi_skywatcherAltAzMount
/usr/bin/indi_smartfocus_focus
/usr/bin/indi_snapcap
/usr/bin/indi_sqm_weather
/usr/bin/indi_star2000
/usr/bin/indi_steeldrive2_focus
/usr/bin/indi_steeldrive_focus
/usr/bin/indi_synscan_telescope
/usr/bin/indi_synscanlegacy_telescope
/usr/bin/indi_tcfs3_focus
/usr/bin/indi_tcfs_focus
/usr/bin/indi_teenastro_focus
/usr/bin/indi_temma_telescope
/usr/bin/indi_trutech_wheel
/usr/bin/indi_uranus_weather
/usr/bin/indi_usbdewpoint
/usr/bin/indi_usbfocusv3_focus
/usr/bin/indi_v4l2_ccd
/usr/bin/indi_vantage_weather
/usr/bin/indi_wanderer_cover
/usr/bin/indi_wanderer_lite_rotator
/usr/bin/indi_wanderer_rotator_lite_v2
/usr/bin/indi_wanderer_rotator_mini
/usr/bin/indi_wandererbox_plus_v3
/usr/bin/indi_wandererbox_pro_v3
/usr/bin/indi_wanderercover_v4_ec
/usr/bin/indi_watchdog
/usr/bin/indi_watcher_weather
/usr/bin/indi_weather_safety_proxy
/usr/bin/indi_xagyl_wheel
/usr/bin/indiserver
/usr/bin/shelyak_usis

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/80-dbk21-camera.rules
/usr/lib/udev/rules.d/99-indi_auxiliary.rules

%files data
%defattr(-,root,root,-)
/usr/share/indi/drivers.xml
/usr/share/indi/indi_tcfs_sk.xml
/usr/share/indi/shelyak_boards.json

%files dev
%defattr(-,root,root,-)
/usr/include/libindi/abstractbaseclient.h
/usr/include/libindi/alignment/AlignmentSubsystemForDrivers.h
/usr/include/libindi/alignment/AlignmentSubsystemForMathPlugins.h
/usr/include/libindi/alignment/BasicMathPlugin.h
/usr/include/libindi/alignment/BuiltInMathPlugin.h
/usr/include/libindi/alignment/ClientAPIForAlignmentDatabase.h
/usr/include/libindi/alignment/ClientAPIForMathPluginManagement.h
/usr/include/libindi/alignment/Common.h
/usr/include/libindi/alignment/ConvexHull.h
/usr/include/libindi/alignment/DriverCommon.h
/usr/include/libindi/alignment/InMemoryDatabase.h
/usr/include/libindi/alignment/MapPropertiesToInMemoryDatabase.h
/usr/include/libindi/alignment/MathPlugin.h
/usr/include/libindi/alignment/MathPluginManagement.h
/usr/include/libindi/alignment/NearestMathPlugin.h
/usr/include/libindi/alignment/SVDMathPlugin.h
/usr/include/libindi/alignment/TelescopeDirectionVectorSupportFunctions.h
/usr/include/libindi/base64.h
/usr/include/libindi/baseclient.h
/usr/include/libindi/basedevice.h
/usr/include/libindi/connectionplugins/connectioninterface.h
/usr/include/libindi/connectionplugins/connectionserial.h
/usr/include/libindi/connectionplugins/connectiontcp.h
/usr/include/libindi/defaultdevice.h
/usr/include/libindi/dsp.h
/usr/include/libindi/dsp/convolution.h
/usr/include/libindi/dsp/dspinterface.h
/usr/include/libindi/dsp/manager.h
/usr/include/libindi/dsp/transforms.h
/usr/include/libindi/eventloop.h
/usr/include/libindi/fits.h
/usr/include/libindi/fits_extensions.h
/usr/include/libindi/fitsidi.h
/usr/include/libindi/fitskeyword.h
/usr/include/libindi/hidapi.h
/usr/include/libindi/httplib.h
/usr/include/libindi/indiapi.h
/usr/include/libindi/indibase.h
/usr/include/libindi/indibasetypes.h
/usr/include/libindi/indiccd.h
/usr/include/libindi/indiccdchip.h
/usr/include/libindi/indicom.h
/usr/include/libindi/indicontroller.h
/usr/include/libindi/indicorrelator.h
/usr/include/libindi/indidetector.h
/usr/include/libindi/indidevapi.h
/usr/include/libindi/indidome.h
/usr/include/libindi/indidriver.h
/usr/include/libindi/indidustcapinterface.h
/usr/include/libindi/indielapsedtimer.h
/usr/include/libindi/indifilterinterface.h
/usr/include/libindi/indifilterwheel.h
/usr/include/libindi/indifocuser.h
/usr/include/libindi/indifocuserinterface.h
/usr/include/libindi/indigps.h
/usr/include/libindi/indigpsinterface.h
/usr/include/libindi/indiguiderinterface.h
/usr/include/libindi/indijson.hpp
/usr/include/libindi/indilightboxinterface.h
/usr/include/libindi/indilogger.h
/usr/include/libindi/indimacros.h
/usr/include/libindi/indiproperties.h
/usr/include/libindi/indiproperty.h
/usr/include/libindi/indipropertybasic.h
/usr/include/libindi/indipropertyblob.h
/usr/include/libindi/indipropertylight.h
/usr/include/libindi/indipropertynumber.h
/usr/include/libindi/indipropertyswitch.h
/usr/include/libindi/indipropertytext.h
/usr/include/libindi/indipropertyview.h
/usr/include/libindi/indireceiver.h
/usr/include/libindi/indirotator.h
/usr/include/libindi/indirotatorinterface.h
/usr/include/libindi/indisensorinterface.h
/usr/include/libindi/indisinglethreadpool.h
/usr/include/libindi/indispectrograph.h
/usr/include/libindi/indistandardproperty.h
/usr/include/libindi/inditelescope.h
/usr/include/libindi/inditimer.h
/usr/include/libindi/indiusbdevice.h
/usr/include/libindi/indiutility.h
/usr/include/libindi/indiversion.h
/usr/include/libindi/indiweather.h
/usr/include/libindi/indiweatherinterface.h
/usr/include/libindi/indiwidgettraits.h
/usr/include/libindi/indiwidgetview.h
/usr/include/libindi/inicpp.h
/usr/include/libindi/libastro.h
/usr/include/libindi/lilxml.h
/usr/include/libindi/mounts/lx200driver.h
/usr/include/libindi/mounts/lx200telescope.h
/usr/include/libindi/parentdevice.h
/usr/include/libindi/pid.h
/usr/include/libindi/sdfits.h
/usr/include/libindi/sharedblob.h
/usr/include/libindi/stream/ccvt.h
/usr/include/libindi/stream/ccvt_types.h
/usr/include/libindi/stream/encoder/encoderinterface.h
/usr/include/libindi/stream/encoder/encodermanager.h
/usr/include/libindi/stream/encoder/mjpegencoder.h
/usr/include/libindi/stream/encoder/rawencoder.h
/usr/include/libindi/stream/fpsmeter.h
/usr/include/libindi/stream/gammalut16.h
/usr/include/libindi/stream/jpegutils.h
/usr/include/libindi/stream/recorder/recorderinterface.h
/usr/include/libindi/stream/recorder/recordermanager.h
/usr/include/libindi/stream/recorder/serrecorder.h
/usr/include/libindi/stream/streammanager.h
/usr/include/libindi/stream/uniquequeue.h
/usr/include/libindi/v4l2_builtin_decoder.h
/usr/include/libindi/v4l2_colorspace.h
/usr/include/libindi/v4l2_decode.h
/usr/lib64/libindiAlignmentDriver.so
/usr/lib64/libindiclient.so
/usr/lib64/libindidriver.so
/usr/lib64/libindilx200.so
/usr/lib64/pkgconfig/libindi.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libindiAlignmentDriver.so.2.0.8
/V3/usr/lib64/libindiclient.so.2.0.8
/V3/usr/lib64/libindidriver.so.2.0.8
/V3/usr/lib64/libindilx200.so.2.0.8
/usr/lib64/libindiAlignmentDriver.so.2
/usr/lib64/libindiAlignmentDriver.so.2.0.8
/usr/lib64/libindiclient.so.2
/usr/lib64/libindiclient.so.2.0.8
/usr/lib64/libindidriver.so.2
/usr/lib64/libindidriver.so.2.0.8
/usr/lib64/libindilx200.so.2
/usr/lib64/libindilx200.so.2.0.8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/indi/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/indi/321af0a4f65053aa5df091a79465916cfb42cea3
/usr/share/package-licenses/indi/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/indi/85c02e0cb8c0aaac8a3f3eed04bc1a097e145883
/usr/share/package-licenses/indi/b386b371ce94933e63ced1052aa72a60da5485ff
/usr/share/package-licenses/indi/c237597680be0db41fc5ca7249bc540b8825371e
