#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : indi
Version  : 1.7.4
Release  : 1
URL      : https://github.com/indilib/indi/archive/v1.7.4.tar.gz
Source0  : https://github.com/indilib/indi/archive/v1.7.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause CC-BY-3.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 MIT
Requires: indi-bin = %{version}-%{release}
Requires: indi-data = %{version}-%{release}
Requires: indi-lib = %{version}-%{release}
Requires: indi-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : cfitsio-dev
BuildRequires : curl-dev
BuildRequires : extra-cmake-modules pkgconfig(glib-2.0)
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : gsl-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libnova-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gsl)
BuildRequires : pkgconfig(libraw)
BuildRequires : pkgconfig(libraw_r)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : tiff-dev
BuildRequires : zlib-dev

%description
libindi v1.6.0
==============
The code here demonstrates the use of INDI, an Instrument-Neutral Device
Interface protocol. See http://www.clearskyinstitute.com/INDI/INDI.pdf.

%package bin
Summary: bin components for the indi package.
Group: Binaries
Requires: indi-data = %{version}-%{release}
Requires: indi-license = %{version}-%{release}

%description bin
bin components for the indi package.


%package data
Summary: data components for the indi package.
Group: Data

%description data
data components for the indi package.


%package dev
Summary: dev components for the indi package.
Group: Development
Requires: indi-lib = %{version}-%{release}
Requires: indi-bin = %{version}-%{release}
Requires: indi-data = %{version}-%{release}
Provides: indi-devel = %{version}-%{release}

%description dev
dev components for the indi package.


%package lib
Summary: lib components for the indi package.
Group: Libraries
Requires: indi-data = %{version}-%{release}
Requires: indi-license = %{version}-%{release}

%description lib
lib components for the indi package.


%package license
Summary: license components for the indi package.
Group: Default

%description license
license components for the indi package.


%prep
%setup -q -n indi-1.7.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548179539
mkdir -p clr-build
pushd clr-build
%cmake ../libindi
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1548179539
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/indi
cp 3rdparty/asi-common/license.txt %{buildroot}/usr/share/package-licenses/indi/3rdparty_asi-common_license.txt
cp 3rdparty/fxload/COPYING %{buildroot}/usr/share/package-licenses/indi/3rdparty_fxload_COPYING
cp 3rdparty/indi-aagcloudwatcher/LICENSE.txt %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-aagcloudwatcher_LICENSE.txt
cp 3rdparty/indi-apogee/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-apogee_COPYING.LIB
cp 3rdparty/indi-asi/COPYING.LGPL %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-asi_COPYING.LGPL
cp 3rdparty/indi-eqmod/COPYING %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-eqmod_COPYING
cp 3rdparty/indi-gphoto/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-gphoto_COPYING.LIB
cp 3rdparty/indi-inovaplx/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-inovaplx_COPYING.LIB
cp 3rdparty/indi-nightscape/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-nightscape_COPYING.LIB
cp 3rdparty/indi-radiosim/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-radiosim_COPYING.LIB
cp 3rdparty/indi-rtlsdr/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-rtlsdr_COPYING.LIB
cp 3rdparty/indi-sbig/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-sbig_COPYING.LIB
cp 3rdparty/indi-spectracyber/copying.lib %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-spectracyber_copying.lib
cp 3rdparty/indi-sx/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_indi-sx_COPYING.LIB
cp 3rdparty/libapogee/LICENSE %{buildroot}/usr/share/package-licenses/indi/3rdparty_libapogee_LICENSE
cp 3rdparty/libdspau/LICENSE.txt %{buildroot}/usr/share/package-licenses/indi/3rdparty_libdspau_LICENSE.txt
cp 3rdparty/libfishcamp/COPYING.LIB %{buildroot}/usr/share/package-licenses/indi/3rdparty_libfishcamp_COPYING.LIB
cp 3rdparty/libfli/LICENSE.BSD %{buildroot}/usr/share/package-licenses/indi/3rdparty_libfli_LICENSE.BSD
cp 3rdparty/libinovasdk/LICENSE.lib %{buildroot}/usr/share/package-licenses/indi/3rdparty_libinovasdk_LICENSE.lib
cp 3rdparty/libsbig/LICENSE.firmware %{buildroot}/usr/share/package-licenses/indi/3rdparty_libsbig_LICENSE.firmware
cp LICENSE %{buildroot}/usr/share/package-licenses/indi/LICENSE
cp debian/asi-common/copyright %{buildroot}/usr/share/package-licenses/indi/debian_asi-common_copyright
cp debian/astrometry-data/copyright %{buildroot}/usr/share/package-licenses/indi/debian_astrometry-data_copyright
cp debian/fxload-libusb/copyright %{buildroot}/usr/share/package-licenses/indi/debian_fxload-libusb_copyright
cp debian/fxload/copyright %{buildroot}/usr/share/package-licenses/indi/debian_fxload_copyright
cp debian/gsc/copyright %{buildroot}/usr/share/package-licenses/indi/debian_gsc_copyright
cp debian/indi-aagcloudwatcher/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-aagcloudwatcher_copyright
cp debian/indi-apogee/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-apogee_copyright
cp debian/indi-dsi/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-dsi_copyright
cp debian/indi-ffmv/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-ffmv_copyright
cp debian/indi-gpsd/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-gpsd_copyright
cp debian/indi-gpsnmea/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-gpsnmea_copyright
cp debian/indi-maxdomeii/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-maxdomeii_copyright
cp debian/indi-mgen/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-mgen_copyright
cp debian/indi-nexdome/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-nexdome_copyright
cp debian/indi-nexstarevo/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-nexstarevo_copyright
cp debian/indi-nightscape/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-nightscape_copyright
cp debian/indi-sbig/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-sbig_copyright
cp debian/indi-webcam/copyright %{buildroot}/usr/share/package-licenses/indi/debian_indi-webcam_copyright
cp debian/libfishcamp/copyright %{buildroot}/usr/share/package-licenses/indi/debian_libfishcamp_copyright
cp debian/libindi-all/copyright %{buildroot}/usr/share/package-licenses/indi/debian_libindi-all_copyright
cp debian/libqhy/copyright %{buildroot}/usr/share/package-licenses/indi/debian_libqhy_copyright
cp debian/libsbig/copyright %{buildroot}/usr/share/package-licenses/indi/debian_libsbig_copyright
cp debian/obsolete/fliusb/copyright %{buildroot}/usr/share/package-licenses/indi/debian_obsolete_fliusb_copyright
cp libindi/COPYING.BSD %{buildroot}/usr/share/package-licenses/indi/libindi_COPYING.BSD
cp libindi/COPYING.GPL %{buildroot}/usr/share/package-licenses/indi/libindi_COPYING.GPL
cp libindi/COPYING.LGPL %{buildroot}/usr/share/package-licenses/indi/libindi_COPYING.LGPL
cp libindi/LICENSE %{buildroot}/usr/share/package-licenses/indi/libindi_LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/lib/udev/rules.d/99-flipflat.rules
/lib/udev/rules.d/99-focusers.rules
/lib/udev/rules.d/99-gpusb.rules
/lib/udev/rules.d/99-vantage.rules
/usr/usr/lib64/indi/MathPlugins/libindi_SVD_MathPlugin.so

%files bin
%defattr(-,root,root,-)
/usr/bin/indi_arduinost4
/usr/bin/indi_astrometry
/usr/bin/indi_baader_dome
/usr/bin/indi_celestron_gps
/usr/bin/indi_dmfc_focus
/usr/bin/indi_dsc_telescope
/usr/bin/indi_eval
/usr/bin/indi_flipflat
/usr/bin/indi_gemini_focus
/usr/bin/indi_getprop
/usr/bin/indi_gpusb
/usr/bin/indi_hid_test
/usr/bin/indi_hitecastrodc_focus
/usr/bin/indi_ieq_telescope
/usr/bin/indi_imager_agent
/usr/bin/indi_integra_focus
/usr/bin/indi_ioptronHC8406
/usr/bin/indi_ioptronv3_telescope
/usr/bin/indi_joystick
/usr/bin/indi_lakeside_focus
/usr/bin/indi_lx200_10micron
/usr/bin/indi_lx200_16
/usr/bin/indi_lx200_OnStep
/usr/bin/indi_lx200ap
/usr/bin/indi_lx200ap_experimental
/usr/bin/indi_lx200ap_gtocp2
/usr/bin/indi_lx200autostar
/usr/bin/indi_lx200basic
/usr/bin/indi_lx200classic
/usr/bin/indi_lx200fs2
/usr/bin/indi_lx200gemini
/usr/bin/indi_lx200generic
/usr/bin/indi_lx200gotonova
/usr/bin/indi_lx200gps
/usr/bin/indi_lx200pulsar2
/usr/bin/indi_lx200ss2000pc
/usr/bin/indi_lx200zeq25
/usr/bin/indi_lynx_focus
/usr/bin/indi_mbox_weather
/usr/bin/indi_meta_weather
/usr/bin/indi_microtouch_focus
/usr/bin/indi_moonlite_focus
/usr/bin/indi_nfocus
/usr/bin/indi_nightcrawler_focus
/usr/bin/indi_nstep_focus
/usr/bin/indi_optec_wheel
/usr/bin/indi_paramount_telescope
/usr/bin/indi_perfectstar_focus
/usr/bin/indi_pmc8_telescope
/usr/bin/indi_pyxis_rotator
/usr/bin/indi_quantum_wheel
/usr/bin/indi_robo_focus
/usr/bin/indi_rolloff_dome
/usr/bin/indi_script_dome
/usr/bin/indi_script_telescope
/usr/bin/indi_sestosenso_focus
/usr/bin/indi_setprop
/usr/bin/indi_simulator_ccd
/usr/bin/indi_simulator_dome
/usr/bin/indi_simulator_focus
/usr/bin/indi_simulator_gps
/usr/bin/indi_simulator_guide
/usr/bin/indi_simulator_sqm
/usr/bin/indi_simulator_telescope
/usr/bin/indi_simulator_weather
/usr/bin/indi_simulator_wheel
/usr/bin/indi_skycommander_telescope
/usr/bin/indi_skysafari
/usr/bin/indi_skywatcherAltAzMount
/usr/bin/indi_skywatcherAltAzSimple
/usr/bin/indi_smartfocus_focus
/usr/bin/indi_snapcap
/usr/bin/indi_sqm_weather
/usr/bin/indi_star2000
/usr/bin/indi_steeldrive_focus
/usr/bin/indi_synscan_telescope
/usr/bin/indi_tcfs3_focus
/usr/bin/indi_tcfs_focus
/usr/bin/indi_temma_telescope
/usr/bin/indi_trutech_wheel
/usr/bin/indi_usbdewpoint
/usr/bin/indi_usbfocusv3_focus
/usr/bin/indi_v4l2_ccd
/usr/bin/indi_vantage_weather
/usr/bin/indi_watchdog
/usr/bin/indi_watcher_weather
/usr/bin/indi_wunderground_weather
/usr/bin/indi_xagyl_wheel
/usr/bin/indiserver

%files data
%defattr(-,root,root,-)
/usr/share/indi/drivers.xml
/usr/share/indi/indi_tcfs_sk.xml

%files dev
%defattr(-,root,root,-)
/usr/include/libindi/alignment/AlignmentSubsystemForDrivers.h
/usr/include/libindi/alignment/AlignmentSubsystemForMathPlugins.h
/usr/include/libindi/alignment/BasicMathPlugin.h
/usr/include/libindi/alignment/BuiltInMathPlugin.h
/usr/include/libindi/alignment/ClientAPIForAlignmentDatabase.h
/usr/include/libindi/alignment/ClientAPIForMathPluginManagement.h
/usr/include/libindi/alignment/Common.h
/usr/include/libindi/alignment/ConvexHull.h
/usr/include/libindi/alignment/DriverCommon.h
/usr/include/libindi/alignment/InMemoryDatabase.h
/usr/include/libindi/alignment/MapPropertiesToInMemoryDatabase.h
/usr/include/libindi/alignment/MathPlugin.h
/usr/include/libindi/alignment/MathPluginManagement.h
/usr/include/libindi/alignment/SVDMathPlugin.h
/usr/include/libindi/alignment/TelescopeDirectionVectorSupportFunctions.h
/usr/include/libindi/base64.h
/usr/include/libindi/baseclient.h
/usr/include/libindi/basedevice.h
/usr/include/libindi/connectionplugins/connectioninterface.h
/usr/include/libindi/connectionplugins/connectionserial.h
/usr/include/libindi/connectionplugins/connectiontcp.h
/usr/include/libindi/defaultdevice.h
/usr/include/libindi/eventloop.h
/usr/include/libindi/hidapi.h
/usr/include/libindi/indiapi.h
/usr/include/libindi/indibase.h
/usr/include/libindi/indibasetypes.h
/usr/include/libindi/indiccd.h
/usr/include/libindi/indicom.h
/usr/include/libindi/indicontroller.h
/usr/include/libindi/indidetector.h
/usr/include/libindi/indidevapi.h
/usr/include/libindi/indidome.h
/usr/include/libindi/indidriver.h
/usr/include/libindi/indidustcapinterface.h
/usr/include/libindi/indifilterinterface.h
/usr/include/libindi/indifilterwheel.h
/usr/include/libindi/indifocuser.h
/usr/include/libindi/indifocuserinterface.h
/usr/include/libindi/indigps.h
/usr/include/libindi/indiguiderinterface.h
/usr/include/libindi/indilightboxinterface.h
/usr/include/libindi/indilogger.h
/usr/include/libindi/indiproperty.h
/usr/include/libindi/indirotator.h
/usr/include/libindi/indirotatorinterface.h
/usr/include/libindi/indistandardproperty.h
/usr/include/libindi/inditelescope.h
/usr/include/libindi/indiusbdevice.h
/usr/include/libindi/indiversion.h
/usr/include/libindi/indiweather.h
/usr/include/libindi/lilxml.h
/usr/include/libindi/stream/ccvt.h
/usr/include/libindi/stream/ccvt_types.h
/usr/include/libindi/stream/encoder/encoderinterface.h
/usr/include/libindi/stream/encoder/encodermanager.h
/usr/include/libindi/stream/encoder/mjpegencoder.h
/usr/include/libindi/stream/encoder/rawencoder.h
/usr/include/libindi/stream/jpegutils.h
/usr/include/libindi/stream/recorder/recorderinterface.h
/usr/include/libindi/stream/recorder/recordermanager.h
/usr/include/libindi/stream/recorder/serrecorder.h
/usr/include/libindi/stream/streammanager.h
/usr/include/libindi/v4l2_builtin_decoder.h
/usr/include/libindi/v4l2_colorspace.h
/usr/include/libindi/v4l2_decode.h
/usr/lib64/libindiAlignmentDriver.so
/usr/lib64/libindidriver.so
/usr/lib64/pkgconfig/libindi.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libindiAlignmentDriver.so.1
/usr/lib64/libindiAlignmentDriver.so.1.7.4
/usr/lib64/libindidriver.so.1
/usr/lib64/libindidriver.so.1.7.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/indi/3rdparty_asi-common_license.txt
/usr/share/package-licenses/indi/3rdparty_fxload_COPYING
/usr/share/package-licenses/indi/3rdparty_indi-aagcloudwatcher_LICENSE.txt
/usr/share/package-licenses/indi/3rdparty_indi-apogee_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_indi-asi_COPYING.LGPL
/usr/share/package-licenses/indi/3rdparty_indi-eqmod_COPYING
/usr/share/package-licenses/indi/3rdparty_indi-gphoto_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_indi-inovaplx_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_indi-nightscape_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_indi-radiosim_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_indi-rtlsdr_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_indi-sbig_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_indi-spectracyber_copying.lib
/usr/share/package-licenses/indi/3rdparty_indi-sx_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_libapogee_LICENSE
/usr/share/package-licenses/indi/3rdparty_libdspau_LICENSE.txt
/usr/share/package-licenses/indi/3rdparty_libfishcamp_COPYING.LIB
/usr/share/package-licenses/indi/3rdparty_libfli_LICENSE.BSD
/usr/share/package-licenses/indi/3rdparty_libinovasdk_LICENSE.lib
/usr/share/package-licenses/indi/3rdparty_libsbig_LICENSE.firmware
/usr/share/package-licenses/indi/LICENSE
/usr/share/package-licenses/indi/debian_asi-common_copyright
/usr/share/package-licenses/indi/debian_astrometry-data_copyright
/usr/share/package-licenses/indi/debian_fxload-libusb_copyright
/usr/share/package-licenses/indi/debian_fxload_copyright
/usr/share/package-licenses/indi/debian_gsc_copyright
/usr/share/package-licenses/indi/debian_indi-aagcloudwatcher_copyright
/usr/share/package-licenses/indi/debian_indi-apogee_copyright
/usr/share/package-licenses/indi/debian_indi-dsi_copyright
/usr/share/package-licenses/indi/debian_indi-ffmv_copyright
/usr/share/package-licenses/indi/debian_indi-gpsd_copyright
/usr/share/package-licenses/indi/debian_indi-gpsnmea_copyright
/usr/share/package-licenses/indi/debian_indi-maxdomeii_copyright
/usr/share/package-licenses/indi/debian_indi-mgen_copyright
/usr/share/package-licenses/indi/debian_indi-nexdome_copyright
/usr/share/package-licenses/indi/debian_indi-nexstarevo_copyright
/usr/share/package-licenses/indi/debian_indi-nightscape_copyright
/usr/share/package-licenses/indi/debian_indi-sbig_copyright
/usr/share/package-licenses/indi/debian_indi-webcam_copyright
/usr/share/package-licenses/indi/debian_libfishcamp_copyright
/usr/share/package-licenses/indi/debian_libindi-all_copyright
/usr/share/package-licenses/indi/debian_libqhy_copyright
/usr/share/package-licenses/indi/debian_libsbig_copyright
/usr/share/package-licenses/indi/debian_obsolete_fliusb_copyright
/usr/share/package-licenses/indi/libindi_COPYING.BSD
/usr/share/package-licenses/indi/libindi_COPYING.GPL
/usr/share/package-licenses/indi/libindi_COPYING.LGPL
/usr/share/package-licenses/indi/libindi_LICENSE
